### ISSUE TITLE
multi-GPU support

### ISSUE THREAD

**Issue by xiaoiker** [plai-group/flexible-video-diffusion-modeling#1]
Hi, thanks for releasing this great project. One small question  is that seems the code does not support Multi-GPU training. Is this true, if not how can set it? Best!

**Comment by xiaoiker** [comment]
Hi 

Thanks a lot for your response. I run my code on GCP with 4 A100. The code works well when using: python video_train.py --batch_size 2 . 

But while I try to run it using 3 GPUs using this line:  CUDA_VISIBLE_DEVICES=1,2,3 python video_train.py --batch_size 6, for sure there will be a OOM issue. Then I tried to manually change the WORLD_SIZE in dist_util.py to 3, then when I run this command again, it just stucked there, nothing happen. 

Do you have any suggestion. (Srun for GCP seems complicated)

Best

**Comment by xiaoiker** [comment]
Oh seems mpiexec works for this issue.

**Comment by wsgharvey** [comment]
I should probably have made it clearer that the `--batch_size` argument refers to the batch size _per GPU_ rather than the total batch size. So e.g. my example script was using a batch size of 4 split over 2 GPUs and you probably need to use `--batch_size 2` to avoid the OOM error (which is a total batch size of 6 over 3 GPUs).

And glad to hear that `mpiexec` fixed it, was about to suggest that :D
