### ISSUE TITLE
Log-uniform scale sampling

### ISSUE THREAD

**Issue by neverix** [plai-group/flexible-video-diffusion-modeling#6]
The paper states that group scales are sampled uniformly when creating training samples.

<img src="https://github.com/plai-group/flexible-video-diffusion-modeling/assets/46641404/93cae030-9593-4bf6-b766-fbfe1194c972">

However, the [implementation](https://github.com/plai-group/flexible-video-diffusion-modeling/blob/4c3d78b07fd3cd5dd0019ed5fcac9579813f26ff/improved_diffusion/train_util.py#L176) subtracts 0.999 from `n_group` before exponentiating. This means that the scale can explode 1000x. Is this intentional?

**Comment by wsgharvey** [comment]
Hi, thanks for pointing this out and sorry for the slow response. 

I have double-checked and the code used in our experiments is the same as in the implementation we link to. It seems that this is a mistake in the algorithm in the paper, and is not intentional.

It looks like the difference is the upper bound on the log-uniform distribution is $\frac{N}{n_\text{group} - 0.999}$ in the code and $\frac{N-1}{n_\text{group}}$ in the algorithm. These will be quite different when:
- $n_\text{group} = 1$ - but the sampled $s_\text{group}$ is actually irrelevant in that case anyway - as the code will just multiply $s_\text{group}$ by zero when sampling $x_\text{group}$ and then construct $\mathcal{G} := \\{ x_\text{group} \\}$ no matter what $s_\text{group}$ is.
- $n_\text{group} = 2$ - in this case $s_\text{group}$ will be upper-bounded by roughly $N$ in the code or roughly $\frac{N}{2}$ in the algorithm.
- $n_\text{group} = 3$ - in this case $s_\text{group}$ will be upper-bounded by roughly $\frac{N}{2}$ in the code or roughly $\frac{N}{3}$ in the algorithm.

I would say that the versions in the code make more sense as they allow for the broader distribution - e.g. when we want to space three points across a distance $N$ then it is possible to space them up to $\frac{N}{2}$ apart, not just $\frac{N}{3}$. Arguably an ideal expression for the upper bound would be $\frac{N}{n_\text{group} - 1}$, but I think we edited this to $\frac{N}{n_\text{group} - 0.999}$ as a simple way to avoid nans when $n_\text{group} = 1$.

We will do an update of the paper on arxiv in the next few weeks and fix the algorithm there.

Thanks again for pointing this out!
